(async function () {
  try {
    a.b;
  } catch (err) {
    // reference error
    console.log(err);
  }
});
